version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allowed_updates:
    - match:
        dependency_type: "production"
        update_type: "all"

